### ISSUE TITLE
Error after executing 02_deployment.yml

### ISSUE THREAD

**Issue by omniscient** [trondhindenes/ecr-updater#1]
After following steps in the readme, I get the following error which I am not too sure what's up with. Can you help me decipher what that might mean please?

`container_linux.go:247: starting container process caused "process_linux.go:295: setting oom score for ready process caused \"write /proc/10349/oom_score_adj: invalid argument\""`

**Comment by omniscient** [comment]
I forgot to base64 the values so they ended up fubar. Now the container seems to be updading the ecr registry entry correctly but when I try to pull images I get the following:

ErrImagePull: rpc error: code = Unknown desc = unauthorized: authentication required

**Comment by trondhindenes** [comment]
hm that's strange. Are you configuring `imagePullSecrets` as described here ? https://github.com/trondhindenes/ecr-updater/blob/master/03_pullsecret_test.yml

**Comment by trondhindenes** [comment]
also the output of the ecrupdater container might contain some hints regarding what's wrong.

**Comment by superdevofficial** [comment]
Hi,
Same issue with Rancher 2.1.7.
Ecr updater seems to work but Kubernetes cannot pull the image :
```
starting the thing
Sleeping on first startup
Running update loop
starting update loop
pull secret name to search for: ecr
found 1 registry_secrets matching name
Updating secret ecr (type kubernetes.io/dockerconfigjson)
...done. Waiting 3600 seconds
```

**Comment by superdevofficial** [comment]
In my case, the issue is due to secret namespace.
Ecr updater update was updating a secret in default namespace, but the app was in another namespace.

A feature that would be great : support to update a secret created in Rancher for "all namespaces". So when a pod is added to another namespace, it could access to the secret.

**Comment by trondhindenes** [comment]
it does support that, but the secret needs to exist in every namespace. So simply create a secret called "ecr" in every namespace you need, and ECRUpdater should take care of it (given the permissions configured in the example files). This is how we run in production internally.

As far as how Rancher goes I'm not sure (I haven't played much with Rancher 2.0 yet), but I'm pretty sure the limitation is in Kubernetes - it's simply not possible to reference a `pullSecret` in another namespace - at least that's my understanding.

I guess we could add functionality to have ECRupdater auto-create pull secrets in all namespaces based on a single "master" secret or whatever, that shouldn't be too hard to do. Let me know if you have any thoughts on that!

**Comment by omniscient** [comment]
@superdevofficial : Thank you for your reply. My problem was exactly the same. Thanks @trondhindenes for the suggestion to create the same ecr secret in all namespaces. I think this ticket can be closed. Great piece of code by the way!

**Comment by trondhindenes** [comment]
@superdevofficial @omniscient I just pushed an update to this repo which allows auto-creating the secret in all namespaces. Please test it out, and let me know if there are any issues (notice the updated permissions setup in `01_authorization.yml` and the new env var documented in `README.md`)
