### ISSUE TITLE
Better Defaults

### ISSUE THREAD

**Issue by H3JFC** [trondhindenes/ecr-updater#3]
It would be nice if "ECR_CREATE_MISSING" was set to true by default as I think it's a sensible default for ease of use here.

**Comment by trondhindenes** [comment]
hm good question. The reason I left it as-is was to align with the original functionality of this repo (which required secrets to already exist). 

Altho this is a small project, I think it's important to not break functionality unless absolutely required, so I think I'll leave it as-is. I hope that doesn't cause too much problems for you.
